build:
  project: '@project.artifactId@'
  timestamp: '@timestamp@'
  version: '@project.version@'

acs_collector:
  fixedDelay: ${SCHEDULER_TIME:30000}

telegraf:
  url: ${URL_TELEGRAF:http://127.0.0.1:5000/write}

acs:
  url: ${URL_ACS}
  api_key: ${ACS_API_KEY}
  secret_key: ${ACS_SECRET_KEY}
  project_id: ${ACS_PROJECT_ID}

server:
  port: ${SERVER_PORT:8000}