build:
  project: '@project.artifactId@'
  timestamp: '@timestamp@'
  version: '@project.version@'

acs_collector:
  fixedDelay: ${SCHEDULER_TIME:30000}

telegraf:
  url: ${URL_TELEGRAF:http://127.0.0.1:5000/write}

acs:
  url: ${URL_ACS:http://127.0.0.1/client/api}
  api_key: ${ACS_API_KEY:xxx}
  secret_key: ${ACS_SECRET_KEY:xxx}
  project_id: ${ACS_PROJECT_ID:xxx}
  request_validity: ${REQUEST_VALIDITY:30}

server:
  port: ${SERVER_PORT:8000}

pepe:
  logging:
    tags: ${LOGGING_TAGS:default}

spring:
  pid:
    file: ${PID_FILE:/tmp/pepe-chapolin.pid}